config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :settings, only: [:index] do
      collection do
        get :edit
        post :update
      end
    end
    resources :users
    resources :pages
    resources :slides do
      collection do
        get '/:id/image', to: 'slides#destroy_image', as: 'image'
      end
    end
  end

  devise_for :users, :path_prefix => 'my', :controllers => {:registrations => "registrations"}
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#landing', as: :unauthenticated_root
    end
  end
  get '/:url', to: 'pages#show', as: 'page'
end

app/views/admin/pages/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>

<%= simple_form_for([:admin, @page]) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.input :title %>
  <%= f.input :url, wrapper: :input_group, prepend: f.object.active ? unauthenticated_root_url.to_s : authenticated_root_url.to_s %>
  <%= f.label :active, 'Publicar', class: 'control-label' %>
  <%= f.input :active, wrapper: :custom_boolean %>
  <%= f.input :content, input_html: { ckeditor: { toolbar: 'Full' }, class: 'nn-ckeditor-form' }, label: 'Contenido' %>
  <%= f.button :submit, 'Guardar' %>
<% end %>

app/views/admin/pages/edit.html.erb
<div class="row mt-5">
  <div class="col-md-9">
    <h3 class="text-uppercase">Editar página</h3>
  </div>
  <div class="col-md-3">
    <%= link_to 'Volver', admin_pages_path, class: 'btn btn-default btn-block' %>
  </div>
</div>

<%= render 'form', page: @page %>

app/views/admin/pages/index.html.erb
<div class="row mt-5 mb-2">
  <div class="col-md-9">
    <h3 class="text-uppercase">Páginas estáticas</h3>
  </div>
  <div class="col-md-3">
    <%= link_to 'Nueva página', new_admin_page_path, class: 'btn btn-primary btn-block  ' %>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped nn-default-datatable  ">
    <thead>
      <tr>
        <th>Título</th>
        <th>URL</th>
        <th>Publicada</th>
        <th>Autor</th>
        <th style="width:140px;min-width:140px;max-width:140px;" data-orderable="false"></th>
      </tr>
    </thead>
    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.title %></td>
          <td><%= page.url %></td>
          <td><%= page.active ? 'Si' : 'No' %></td>
          <td><%= page.author.email %></td>
          <td><%= link_to 'Ver', admin_page_path(page), class: "btn btn-success btn-xs" %> 
              <%= link_to 'Editar', edit_admin_page_path(page),  class: "btn btn-warning btn-xs" %> 
              <%= link_to 'Eliminar', admin_page_path(page), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: '¿Estás seguro de eliminar esta página?' } if page.destroyable %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/pages/new.html.erb
<div class="row mt-5">
  <div class="col-md-9">
    <h3 class="text-uppercase">Nueva página</h3>
  </div>
  <div class="col-md-3">
    <%= link_to 'Volver', admin_pages_path, class: 'btn btn-default btn-block  ' %>
  </div>
</div>

<%= render 'form', pages: @pages %>

app/views/admin/pages/show.html.erb
<%= render partial: 'pages/template', locals: { page: @page } %>