config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :settings, only: [:index] do
      collection do
        get :edit
        post :update
      end
    end
    resources :users
    resources :pages
    resources :slides do
      collection do
        get '/:id/image', to: 'slides#destroy_image', as: 'image'
      end
    end
  end

  devise_for :users, :path_prefix => 'my', :controllers => {:registrations => "registrations"}
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#landing', as: :unauthenticated_root
    end
  end
  get '/:url', to: 'pages#show', as: 'page'
end

app/models/slide.rb
class Slide < ApplicationRecord
  has_attached_file :image,
                    styles: { original: {},
                              cropped: { processors: [:cropper] } },
                    path: ":rails_root/public/slide_images/:style/:id/:filename",
                    url: "/slide_images/:style/:id/:filename"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_presence_of :image, unless: :video_url?
  validates_presence_of :video_url, unless: :image?, message: 'Debe ingresar una imagen o video'
  validates :position, presence: true
  before_save :save_youtube_id, if: :video_url?

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  def save_youtube_id
    self.video_id = video_url.split("=").last
  end
end

app/controllers/admin/slides_controller.rb
module Admin
  class SlidesController < AdminController
    before_action :set_slide, only: [:show, :edit, :update, :destroy, :show, :destroy_image]

    def index
      @slides = Slide.all.order(position: :desc)
    end

    def edit
    end

    def show
    end

    def create
      @slide = Slide.new(slide_params)
      respond_to do |format|
        if @slide.save
          format.html { redirect_to admin_slides_path, notice: 'Banner creado exitosamente' }
          format.json { render :show, status: :created, location: @slide }
        else
          format.html { render :new }
          format.json { render json: @slide.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @slide.update(slide_params)
          @slide.image.reprocess! if image_edit(params[:slide])
          format.html { redirect_to admin_slides_path, notice: 'Banner actualizado exitosamente' }
          format.json { render :show, status: :ok, location: @slide }
        else
          format.html { render :edit }
          format.json { render json: @slide.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @slide.destroy
      respond_to do |format|
        format.html { redirect_to admin_slides_url, notice: 'Banner eliminado exitosamente' }
        format.json { head :no_content }
      end
    end

    def destroy_image
      if @slide.present?
        @slide.image.destroy
        @slide.save
      end
    end

    private

    def set_slide
      @slide = Slide.find(params[:id])
    end

    def slide_params
      params.require(:slide)
            .permit(:title, :caption, :video_url, :active, :crop_x, :crop_y,
                    :crop_w, :crop_h, :image, :position)
    end
  end
end

app/views/admin/slides/_form.html.erb
<%= simple_form_for([:admin, @slide], 
                      wrapper: :horizontal_form,  
                      wrapper_mappings: {
                        boolean: :horizontal_boolean
                      }) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="banner  ">
    <div class="content">
      <% if f.object.image.exists? && f.object.id %>
        <img src="<%= f.object.image.url(:cropped) %>" class="nn-image-preview" id="nn-cropbox",
        data-full="<%= f.object.image.url(:original) %>", data-width="<%=Paperclip::Geometry.from_file(f.object.image)%>">
      <% else %>
        <img src="<%= asset_path('default.png') %>" class="nn-image-preview" id="nn-cropbox">
      <% end %>
      <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
        <%= f.hidden_field attribute, id: attribute %>
      <% end %>
    </div>
  </div>
  <div id="image-options">
    <% if f.object.image.exists? && f.object.id %>
      <div class=" " data-toggle="buttons" style="width:100%;">
        <button type="button" class="btn btn-success crop-btn" id="slide-crop" style="width:49%;">Editar recorte</button>
        <%= link_to 'Borrar Imagen', image_admin_slides_path(f.object), data: { confirm: '¿Estás seguro que deseas eliminar la imagen?' },
            remote: true, class: 'btn btn-primary', style: "width:49%;", id: 'nn-del-image' %>
      </div>
    <% end %>
  </div>
  <%= f.input :image %>
  <%= f.input :title %>
  <%= f.input :caption %>
  <%= f.input :position %>
  <%= f.input :video_url, input_html: {type: :string } %>
  <%= f.input :active, wrapper: :custom_boolean %>
  <%= f.button :submit, 'Guardar', class: "btn-primary" %>
<% end %>

app/views/admin/slides/destroy_image.js.erb
$('#nn-cropbox').attr('src', '');
$('#nn-cropbox').css('height', '');
$('#nn-cropbox').css('width', '');
$('#nn-cropbox').data('full', '');
$('#nn-cropbox').data('width', '');
$('#nn-image-name').val('');
$('#image-options').hide();

app/views/admin/slides/edit.html.erb
<div class="row mt-5">
  <div class="col-md-9">
    <h3 class="text-uppercase">Editar Banner</h3>
  </div>
  <div class="col-md-3">
    <%= link_to 'Volver', admin_slides_path, class: 'btn btn-default btn-block  ' %>
  </div>
</div>
<%= render 'form', slide: @slide %>

app/views/admin/slides/index.html.erb
<div class="row mt-5 mb-2">
  <div class="col-sm-9">
    <h3 class="text-uppercase">Banner</h3>
  </div>
  <div class="col-sm-3">
    <%= link_to 'Nuevo banner', new_admin_slide_path, class: 'btn btn-primary btn-block  ' %>
  </div>
</div>
<div class="banner">
  <div class="content">
    <%= render partial: 'slides/home_carousel', locals: { slides: @slides.where(active: true) } %>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped nn-default-datatable  ">
    <thead>
      <tr>
        <th>Orden</th>
        <th>Título</th>
        <th>Activo</th>
        <th>Fecha de creación</th>
        <th style="width:140px;min-width:140px;max-width:140px;" data-orderable="false"></th>
      </tr>
    </thead>
    <tbody>
      <% @slides.each do |slide| %>
        <tr>
          <td><%= slide.position %></td>
          <td><%= slide.title %></td>
          <td><%= slide.active ? 'Si' : 'No' %></td>
          <td><%= slide.created_at %></td>
          <td><%= link_to 'Ver', admin_slide_path(slide), class: "btn btn-success btn-xs" %> 
              <%= link_to 'Editar', edit_admin_slide_path(slide),  class: "btn btn-warning btn-xs" %> 
              <%= link_to 'Eliminar', admin_slide_path(slide), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: '¿Estás seguro de eliminar este banner?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/slides/new.html.erb
<div class="row mt-5">
  <div class="col-md-9">
    <h3 class="text-uppercase">Nuevo banner</h3>
  </div>
  <div class="col-md-3">
    <%= link_to 'Volver', admin_slides_path, class: 'btn btn-default btn-block  ' %>
  </div>
</div>

<%= render 'form', slides: @slides %>

app/views/admin/slides/show.html.erb
<div class="banner mt-5">
  <div class="content">
    <%= render partial: 'slides/home_carousel', locals: { slides: [@slide] } %>
  </div>
</div>