config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :settings, only: [:index] do
      collection do
        get :edit
        post :update
      end
    end
    resources :users
    resources :pages
    resources :slides do
      collection do
        get '/:id/image', to: 'slides#destroy_image', as: 'image'
      end
    end
  end

  devise_for :users, :path_prefix => 'my', :controllers => {:registrations => "registrations"}
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#landing', as: :unauthenticated_root
    end
  end
  get '/:url', to: 'pages#show', as: 'page'
end

app/views/layouts/admin/_footer.html.erb
<% if user_signed_in? %>
  <footer class="footer">
    <p class="text-center nnodes">Desarrollado por <a href="http://nnodes.com/" target="_blank">Nnodes</a></p>
  </footer>
<% end %>

app/views/layouts/admin/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <a class="navbar-brand" href="#">
    <img alt="Nnodes" src="<%= asset_path 'logo-w.svg' %>" style="height: 30px;">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", authenticated_root_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if params[:controller] == 'admin/users' %>">
        <%= link_to "Usuarios", admin_users_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if params[:controller] == 'admin/settings' %>">
        <%= link_to "Configuraciones", admin_settings_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if params[:controller] == 'admin/pages' %>">
        <%= link_to "Páginas", admin_pages_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= 'active' if params[:controller] == 'admin/slides' %>">
        <%= link_to "Banner", admin_slides_path, class: "nav-link" %>
      </li>
      <li class="nav-item"><%= link_to 'Cambiar contraseña', edit_user_registration_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
    </ul>
  </div>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>Nnodes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="d-flex flex-column h-100">
    <%= render "layouts/admin/menu"%>
    <div class="container">
      <p id="notice"><%= bootstrap_flash %></p>
      <%= yield %>
    </div>
    <%# render partial: "layouts/admin/footer" %>
  </body>
</html>