config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :settings, only: [:index] do
      collection do
        get :edit
        post :update
      end
    end
    resources :users
    resources :pages
    resources :slides do
      collection do
        get '/:id/image', to: 'slides#destroy_image', as: 'image'
      end
    end
  end

  devise_for :users, :path_prefix => 'my', :controllers => {:registrations => "registrations"}
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'home#landing', as: :unauthenticated_root
    end
  end
  get '/:url', to: 'pages#show', as: 'page'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: { basic: 0, admin: 1 }

  def active_for_authentication?
    super && self.active
  end

  def ability
    @ability ||= Ability.new(self, admin? ? 'Admin' : nil)
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    before_action :set_user, only: [:show, :edit, :update, :destroy, :reservations]

    def index
      respond_to do |format|
        format.html
        format.json { render json: UsersDatatable.new(view_context, {action: params[:action]}) }
        format.xlsx { 
          @users = User.all
          filename = 'Usuarios'
          response.headers['Content-Disposition'] = "attachment; filename='#{filename}.xlsx'"
          render
        }
      end
    end

    def show
    end

    def edit
    end

    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to admin_user_path(@user), notice: 'Usuario creado exitosamente' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to admin_user_path(@user), notice: 'Usuario actualizado exitosamente' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_users_url, notice: 'Usuario eliminado exitosamente' }
        format.json { head :no_content }
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user)
            .permit(:email, :active, :role, :password, :password_confirmation)
    end
  end
end

app/views/admin/users/_form.html.erb
<%= simple_form_for([:admin, @user]) do |f| %>
    <%= f.input :email %>
    <%= f.input :role, collection: User.roles.keys, include_blank: false  %>
    <%= f.input :active, as: :radio_buttons, item_wrapper_class: 'radio-inline' %>
    <%= f.input :password  %>
    <%= f.input :password_confirmation %>
    <div class="row">
      <div class="col-md-4 col-md-offset-8">
        <%= f.button :submit %>
      </div>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<%= render partial: 'layouts/admin/resource/edit',
           locals: { title: 'Editar Usuarios' } %>

app/views/admin/users/index.html.erb
<div class="row mt-5 mb-2">
  <div class="col-md-9">
    <h3 class="text-uppercase">Usuarios</h3>
  </div>
  <div class="col-md-3">
    <%= link_to 'Exportar', admin_users_path(format: :xlsx), class: 'btn btn-primary btn-block' %>
  </div>
</div>
<div class="row mb-5 justify-content-end">
  <div class="col-md-2">
    <p><small>Desde</small></p>
    <%= text_field_tag 'f_start_date', nil , class: "nn-users-date-filter form-control", placeholder: "dd/mm/yyyy", readonly: true %>
  </div>
  <div class="col-md-2">
    <p><small>Hasta</small></p>
    <%= text_field_tag 'f_end_date', (Date.today).strftime('%d/%m/%Y'), class: "nn-users-date-filter form-control", placeholder: "dd/mm/yyyy", readonly: true %>
  </div>
</div>
<div class="table-responsive">
  <table class="table nn-admin-users-datatable display" data-source="<%= admin_users_url(format: 'json') %>">
    <thead>
      <tr>
        <th>ID</th>
        <th>Email</th>
        <th>Rol</th>
        <th>Registro</th>
        <th>Activo</th>
        <th style="width:140px;min-width:140px;max-width:140px;" data-orderable="false"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/admin/users/show.html.erb
<div class="row mt-5">
  <div class="col-md-8">
    <h3 class="text-uppercase">Usuario Nº <%= @user.id %></h3>
  </div>
  <div class="col-md-2 col-xs-6">
    <%= link_to 'Editar', edit_admin_user_path(@user), class: "btn btn-warning btn-block  "%>
  </div>
  <div class="col-md-2 col-xs-6">
    <%= link_to 'Volver', admin_users_path, class: "btn btn-default btn-block  "%>
  </div>
</div>
<div class="row">
  <div class="col-md-5">
    <table class="table table-striped">
    <caption>Detalles</caption>
      <tbody>
        <tr>
          <td>Email</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>Rol</td>
          <td><%= @user.role %></td>
        </tr>
        <tr>
          <td>Registro</td>
          <td><%= l @user.created_at %></td>
        </tr>
        <tr>
          <td>Activo</td>
          <td><%= @user.active ? '<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>'.html_safe : '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>'.html_safe %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>